apiVersion: 1
datasources:
- name: influxdb
  orgId: 1
  type: influxdb
  access: Proxy
  url: http://influxdb-service:8086
  database: telegraf
  isDefault: false
  version: 1
  editable: false
  basicAuth: false
  basicAuthUser: admin
  basicAuthPassword: pass
