apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      name: phpmyadmin-pod
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin-container
          image: phpmyadmin
          imagePullPolicy: Never
          ports:
          - containerPort: 5000
            name: phpmyadmin
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            exec:
              command:
              - /bin/sh
              - -c
              - 'pgrep nginx && pgrep php-fpm7'

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    name: phpmyadmin
    targetPort: 5000
  externalTrafficPolicy: Cluster
  type: LoadBalancer
