apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
          - containerPort: 20
            hostPort: 20
          - containerPort: 21
            hostPort: 21
          - containerPort: 21009
            hostPort: 21009
          - containerPort: 21010
            hostPort: 21010
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
          tcpSocket:
            port: 21

---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - port: 20
      targetPort: 20
      name: ftps-data
      protocol: TCP
    - port: 21
      targetPort: 21
      name: ftps
      protocol: TCP
    - port: 21009
      targetPort: 21009
      name: passive1
      protocol: TCP
    - port: 21010
      targetPort: 21010
      name: passive2
      protocol: TCP
  externalTrafficPolicy: Cluster
